# Generated by Django 5.2.5 on 2025-09-23 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTCO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название услуги', max_length=200, verbose_name='Наименование')),
                ('description', models.TextField(help_text='Описание услуги', verbose_name='Описание')),
                ('is_deleted', models.BooleanField(default=False, help_text='Помечена ли услуга как удаленная', verbose_name='Статус удален')),
                ('image_url', models.URLField(blank=True, help_text='Ссылка на изображение услуги', null=True, verbose_name='URL изображения')),
                ('fullDescription', models.TextField(help_text='Подробное описание услуги с включенными сервисами', verbose_name='Полное описание')),
                ('price', models.DecimalField(decimal_places=2, help_text='Стоимость услуги в рублях', max_digits=12, verbose_name='Стоимость')),
            ],
            options={
                'verbose_name': 'Услуга TCO',
                'verbose_name_plural': 'Услуги TCO',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('deleted', 'Удалена'), ('formed', 'Сформирована'), ('completed', 'Завершена'), ('rejected', 'Отклонена')], default='draft', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('formed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата формирования')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Рассчитывается при завершении заявки', max_digits=15, null=True, verbose_name='Общая стоимость')),
                ('duration_years', models.PositiveIntegerField(blank=True, help_text='Рассчитывается при завершении заявки', null=True, verbose_name='Срок эксплуатации (лет)')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_requests', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='moderated_requests', to=settings.AUTH_USER_MODEL, verbose_name='Модератор')),
            ],
            options={
                'verbose_name': 'Расчет',
                'verbose_name_plural': 'Расчеты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CalculationService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Количество единиц услуги', verbose_name='Количество')),
                ('calculation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calculation_services', to='main.calculation', verbose_name='Расчет')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calculation_services', to='main.servicetco', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Услуга в расчете',
                'verbose_name_plural': 'Услуги в расчетах',
                'ordering': ['service__name'],
            },
        ),
        migrations.AddConstraint(
            model_name='calculation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'draft')), fields=('creator', 'status'), name='unique_draft_per_user'),
        ),
        migrations.AddConstraint(
            model_name='calculationservice',
            constraint=models.UniqueConstraint(fields=('calculation', 'service'), name='unique_calculation_service'),
        ),
    ]
