# Generated by Django 5.2.5 on 2025-09-23 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetco',
            name='price_type',
            field=models.CharField(choices=[('one_time', 'Единовременная'), ('monthly', 'Ежемесячная'), ('yearly', 'Ежегодная')], default='one_time', help_text='Единовременная, ежемесячная или ежегодная оплата', max_length=20, verbose_name='Тип стоимости'),
        ),
    ]
