# Generated by Django 5.2.5 on 2025-09-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_servicetco_price_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculation',
            name='duration_years',
        ),
        migrations.AddField(
            model_name='calculation',
            name='duration_months',
            field=models.PositiveIntegerField(blank=True, help_text='Рассчитывается при завершении заявки', null=True, verbose_name='Срок эксплуатации (месяцев)'),
        ),
    ]
