# Generated by Django 5.2.5 on 2025-09-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_calculation_duration_years_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculation',
            name='end_date',
            field=models.DateField(blank=True, help_text='Дата окончания эксплуатации актива', null=True, verbose_name='Дата окончания эксплуатации'),
        ),
        migrations.AddField(
            model_name='calculation',
            name='start_date',
            field=models.DateField(blank=True, help_text='Дата начала эксплуатации актива', null=True, verbose_name='Дата начала эксплуатации'),
        ),
    ]
