# Generated by Django 5.2.5 on 2025-09-30 15:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_calculation_end_date_calculation_start_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Calculation',
            new_name='CalculationTCO',
        ),
        migrations.AlterModelOptions(
            name='calculationtco',
            options={'ordering': ['-created_at'], 'verbose_name': 'Расчет TCO', 'verbose_name_plural': 'Расчеты TCO'},
        ),
    ]
