# Generated by Django 5.2.5 on 2025-01-27 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_calculation_end_date_calculation_start_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Calculation',
            new_name='CalculationTCO',
        ),
    ]