# Generated by Django 5.2.5 on 2025-10-05 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
