# Generated by Django 5.2.5 on 2025-12-24 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_fix_foreign_keys'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.URLField(help_text='Ссылка на файл в MinIO', max_length=500, verbose_name='URL файла')),
                ('file_type', models.CharField(choices=[('photo', 'Фото'), ('video', 'Видео')], help_text='Тип медиа-файла: фото или видео', max_length=10, verbose_name='Тип файла')),
                ('is_deleted', models.BooleanField(default=False, help_text='Помечен ли медиа-файл как удаленный', verbose_name='Статус удален')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('service', models.ForeignKey(help_text='Услуга, к которой относится медиа-файл', on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='main.servicetco', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Медиа-файл услуги',
                'verbose_name_plural': 'Медиа-файлы услуг',
                'ordering': ['id'],
            },
        ),
    ]
